apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: mnist-using-arcface-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.20, pipelines.kubeflow.org/pipeline_compilation_time: '2023-05-18T12:25:58.636446',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "CT pipeline", "name":
      "mnist using arcface"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.20}
spec:
  entrypoint: mnist-using-arcface
  templates:
  - name: analysis-total
    container:
      image: chromatices/mnist-analysis:latest
      resources:
        limits: {nvidia.com/gpu: '2', cpu: '2', memory: 10G}
        requests: {cpu: '1', memory: 5G}
      volumeMounts:
      - {mountPath: /data/, name: data}
      - {mountPath: /model, name: train-model}
    outputs:
      parameters:
      - name: analysis-total-accuracy
        valueFrom: {path: /accuracy.json}
      artifacts:
      - {name: mlpipeline-ui-metadata, path: /mlpipeline-ui-metadata.json}
      - {name: mlpipeline-metrics, path: /mlpipeline-metrics.json}
      - {name: analysis-total-accuracy, path: /accuracy.json}
      - {name: analysis-total-confusion_matrix, path: /confusion_matrix.csv}
    metadata:
      annotations: {pipelines.kubeflow.org/task_display_name: analysis}
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.20
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: data
      nfs: {path: /data/home/nfsroot/mnist_pytorch, server: 10.0.1.102}
    - name: train-model
      persistentVolumeClaim: {claimName: train-model-pvc}
  - name: condition-1
    dag:
      tasks:
      - {name: deploy-mar, template: deploy-mar}
  - name: deploy-mar
    container:
      image: chromatices/mnist-deploy:latest
      volumeMounts:
      - {mountPath: /model, name: train-model}
      - {mountPath: /deploy-model, name: deploy-model}
    metadata:
      annotations: {pipelines.kubeflow.org/task_display_name: deploy}
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.20
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: deploy-model
      persistentVolumeClaim: {claimName: deploy-model-pvc}
    - name: train-model
      persistentVolumeClaim: {claimName: train-model-pvc}
  - name: embedding-data-using-embedding-model
    container:
      image: chromatices/mnist-embedding:latest
      resources:
        limits: {nvidia.com/gpu: '2', cpu: '2', memory: 20G}
        requests: {cpu: '1', memory: 10G}
      volumeMounts:
      - {mountPath: /data/, name: data}
      - {mountPath: /model, name: train-model}
    metadata:
      annotations: {pipelines.kubeflow.org/task_display_name: embedding}
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.20
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: data
      nfs: {path: /data/home/nfsroot/mnist_pytorch, server: 10.0.1.102}
    - name: train-model
      persistentVolumeClaim: {claimName: train-model-pvc}
  - name: load-preprocess-data-pipeline
    container:
      image: chromatices/mnist-pre-data:latest
      resources:
        limits: {cpu: '2', memory: 2G}
        requests: {cpu: '1', memory: 1G}
      volumeMounts:
      - {mountPath: /data/, name: data}
    metadata:
      annotations: {pipelines.kubeflow.org/task_display_name: collect & preprocess
          data}
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.20
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: data
      nfs: {path: /data/home/nfsroot/mnist_pytorch, server: 10.0.1.102}
  - name: mnist-using-arcface
    dag:
      tasks:
      - name: analysis-total
        template: analysis-total
        dependencies: [train-faiss]
      - name: condition-1
        template: condition-1
        when: '{{tasks.analysis-total.outputs.parameters.analysis-total-accuracy}}
          > 0.8'
        dependencies: [analysis-total]
      - name: embedding-data-using-embedding-model
        template: embedding-data-using-embedding-model
        dependencies: [train-embedding-model]
      - {name: load-preprocess-data-pipeline, template: load-preprocess-data-pipeline}
      - name: train-embedding-model
        template: train-embedding-model
        dependencies: [validate-data-pipeline]
      - name: train-faiss
        template: train-faiss
        dependencies: [embedding-data-using-embedding-model]
      - name: validate-data-pipeline
        template: validate-data-pipeline
        dependencies: [load-preprocess-data-pipeline]
  - name: train-embedding-model
    container:
      image: chromatices/mnist-train-model:latest
      resources:
        limits: {nvidia.com/gpu: '2', cpu: '4', memory: 40G}
        requests: {cpu: '2', memory: 20G}
      volumeMounts:
      - {mountPath: /data/, name: data}
      - {mountPath: /model, name: train-model}
    metadata:
      annotations: {pipelines.kubeflow.org/task_display_name: train model}
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.20
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: data
      nfs: {path: /data/home/nfsroot/mnist_pytorch, server: 10.0.1.102}
    - name: train-model
      persistentVolumeClaim: {claimName: train-model-pvc}
  - name: train-faiss
    container:
      image: chromatices/mnist-train-faiss:latest
      resources:
        limits: {nvidia.com/gpu: '2', cpu: '2', memory: 40G}
        requests: {cpu: '1', memory: 20G}
      volumeMounts:
      - {mountPath: /data/, name: data}
      - {mountPath: /model, name: train-model}
    metadata:
      annotations: {pipelines.kubeflow.org/task_display_name: train faiss}
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.20
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: data
      nfs: {path: /data/home/nfsroot/mnist_pytorch, server: 10.0.1.102}
    - name: train-model
      persistentVolumeClaim: {claimName: train-model-pvc}
  - name: validate-data-pipeline
    container:
      image: chromatices/mnist-val-data:latest
      resources:
        limits: {cpu: '4', memory: 15G}
        requests: {cpu: '1', memory: 10G}
      volumeMounts:
      - {mountPath: /data/, name: data}
    metadata:
      annotations: {pipelines.kubeflow.org/task_display_name: validate data}
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.20
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: data
      nfs: {path: /data/home/nfsroot/mnist_pytorch, server: 10.0.1.102}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
