apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: export-metrics-example-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.10, pipelines.kubeflow.org/pipeline_compilation_time: '2022-01-07T13:43:03.150439',
    pipelines.kubeflow.org/pipeline_spec: '{"name": "Export Metrics Example"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.10}
spec:
  entrypoint: export-metrics-example
  templates:
  - name: export-metric-op
    container:
      args: [--mlpipeline-metrics, /tmp/outputs/mlpipeline_metrics/data]
      command:
      - sh
      - -ec
      - |
        program_path=$(mktemp)
        printf "%s" "$0" > "$program_path"
        python3 -u "$program_path" "$@"
      - "def _make_parent_dirs_and_return_path(file_path: str):\n    import os\n \
        \   os.makedirs(os.path.dirname(file_path), exist_ok=True)\n    return file_path\n\
        \ndef export_metric_op(mlpipeline_metrics_path,):\n    import json\n    metrics\
        \ = {\n        \"metrics\": [\n            {\n                \"name\": \"\
        auroc\",\n                \"numberValue\": 0.8, \n            },\n       \
        \     {\n                \"name\": \"f1\",\n                \"numberValue\"\
        : 0.9,\n                \"format\": \"PERCENTAGE\",\n            },\n    \
        \    ],\n    }\n\n    with open(mlpipeline_metrics_path, \"w\") as f:\n  \
        \      json.dump(metrics, f)\n\nimport argparse\n_parser = argparse.ArgumentParser(prog='Export\
        \ metric op', description='')\n_parser.add_argument(\"--mlpipeline-metrics\"\
        , dest=\"mlpipeline_metrics_path\", type=_make_parent_dirs_and_return_path,\
        \ required=True, default=argparse.SUPPRESS)\n_parsed_args = vars(_parser.parse_args())\n\
        \n_outputs = export_metric_op(**_parsed_args)\n"
      image: python:3.7
    outputs:
      artifacts:
      - {name: mlpipeline-metrics, path: /tmp/outputs/mlpipeline_metrics/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.10
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"args": ["--mlpipeline-metrics", {"outputPath": "mlpipeline_metrics"}],
          "command": ["sh", "-ec", "program_path=$(mktemp)\nprintf \"%s\" \"$0\" >
          \"$program_path\"\npython3 -u \"$program_path\" \"$@\"\n", "def _make_parent_dirs_and_return_path(file_path:
          str):\n    import os\n    os.makedirs(os.path.dirname(file_path), exist_ok=True)\n    return
          file_path\n\ndef export_metric_op(mlpipeline_metrics_path,):\n    import
          json\n    metrics = {\n        \"metrics\": [\n            {\n                \"name\":
          \"auroc\",\n                \"numberValue\": 0.8, \n            },\n            {\n                \"name\":
          \"f1\",\n                \"numberValue\": 0.9,\n                \"format\":
          \"PERCENTAGE\",\n            },\n        ],\n    }\n\n    with open(mlpipeline_metrics_path,
          \"w\") as f:\n        json.dump(metrics, f)\n\nimport argparse\n_parser
          = argparse.ArgumentParser(prog=''Export metric op'', description='''')\n_parser.add_argument(\"--mlpipeline-metrics\",
          dest=\"mlpipeline_metrics_path\", type=_make_parent_dirs_and_return_path,
          required=True, default=argparse.SUPPRESS)\n_parsed_args = vars(_parser.parse_args())\n\n_outputs
          = export_metric_op(**_parsed_args)\n"], "image": "python:3.7"}}, "name":
          "Export metric op", "outputs": [{"name": "mlpipeline_metrics", "type": "Metrics"}]}',
        pipelines.kubeflow.org/component_ref: '{}'}
  - name: export-metrics-example
    dag:
      tasks:
      - {name: export-metric-op, template: export-metric-op}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
